// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('Verifier');
var proof = require('../../zokrates/code/proof.json')

contract('TestVerifier', accounts => {
  describe('verify the solidity contract generated by Zokrates executed successfully', function () {
    beforeEach(async function() {
      this.contract = await Verifier.new();
    })

    // - use the contents from proof.json generated from zokrates steps
    it('Test verification with correct proof', async function () {
      assert(await this.contract.verifyTx(proof.proof, proof.inputs))
    })

    it('Test verification with incorrect proof', async function () {
      assert(!await this.contract.verifyTx(proof.proof, [0]))
    })
  })
})
